/**
 * Staatencode-Tabelle der Österreichischen Gesundheitskasse, Stand 22.04.2026
 * (elda.at, Downloads Dienstgeber, „Staatencode-Tabelle", contentid
 * 10008.806565). Reines Datenabbild der Spalten DVSV-Staatenschlüssel,
 * Kurzbezeichnung, KFZ-Kennzeichen, ISOA3 und ISOA2.
 *
 * Kapitel D.11 (Seite 78) verweist für den Staatenschlüssel ausdrücklich auf
 * dieses Verzeichnis: „Im Internet ist das Staatenschlüsselverzeichnis von der
 * Österreichischen Gesundheitskasse für die Verarbeitung im Datensammelsystem
 * unter der Adresse www.elda.at abgelegt." Die Staatsangehörigkeit (`STSL`) der
 * VSNR-Anforderung trägt den ISOA3-Code (Feldtabelle E.30, Feld 16), der
 * Prüfkatalog weist einen Wert außerhalb der Liste mit `F6571` ab.
 *
 * Übernommen sind auch die Einträge, die keinen ISO-Code im engeren Sinn
 * tragen: `stl` (staatenlos), `unb` (Staatsbürgerschaft unbekannt) und die
 * Ersatzcodes mit Unterstrich (`_12` „Afrika, nicht näher zuordenbar" …). Sie
 * stehen so in der Spalte ISOA3; ob ELDA sie im Feld `STSL` annimmt, sagt die
 * Tabelle nicht — abgewiesen wird hier deshalb nur, was gar nicht vorkommt.
 *
 * Das KFZ-Kennzeichen ist **kein** eindeutiger Schlüssel (`F` steht etwa bei
 * drei Einträgen), und die Liste ist dafür nicht abschließend: Kapitel D.12
 * (Seite 79) nennt „weitere KFZ-Kennzeichen" in einem Verzeichnis, das nur den
 * Versicherungsträgern zugänglich ist. Gegen diese Tabelle geprüft wird das
 * Wohnort-Kennzeichen (`WKFZ`) deshalb nicht.
 */
export interface Staat {
  /** DVSV-Staatenschlüssel. */
  readonly schluessel: number;
  /** Kurzbezeichnung laut Tabelle. */
  readonly kurz: string;
  /** Internationales KFZ-Kennzeichen, sofern die Tabelle eines führt. */
  readonly kfz?: string;
  /** ISOA3-Code bzw. der Ersatzcode der Tabelle. */
  readonly isoA3: string;
  /** ISOA2-Code, sofern die Tabelle einen führt. */
  readonly isoA2?: string;
}

/** Stand der übernommenen Staatencode-Tabelle. */
export const STAATEN_STAND = '22.04.2026';

/** Die Staatencode-Tabelle, nach Staatenschlüssel sortiert. */
export const STAATEN: readonly Staat[] = Object.freeze([
  { schluessel: 0, kurz: 'Staatenlos', isoA3: 'stl', isoA2: 'XS' },
  { schluessel: 1, kurz: 'Österreich', kfz: 'A', isoA3: 'AUT', isoA2: 'AT' },
  { schluessel: 2, kurz: 'Deutschland', kfz: 'D', isoA3: 'DEU', isoA2: 'DE' },
  { schluessel: 3, kurz: 'Schweiz', kfz: 'CH', isoA3: 'CHE', isoA2: 'CH' },
  { schluessel: 4, kurz: 'Liechtenstein', kfz: 'FL', isoA3: 'LIE', isoA2: 'LI' },
  { schluessel: 5, kurz: 'Italien', kfz: 'I', isoA3: 'ITA', isoA2: 'IT' },
  { schluessel: 6, kurz: 'ehemaliges Jugoslawien', kfz: 'YU', isoA3: 'YUG', isoA2: 'YU' },
  { schluessel: 7, kurz: 'Ungarn', kfz: 'H', isoA3: 'HUN', isoA2: 'HU' },
  { schluessel: 9, kurz: 'Tschechien', kfz: 'CZ', isoA3: 'CZE', isoA2: 'CZ' },
  { schluessel: 10, kurz: 'Slowakei', kfz: 'SK', isoA3: 'SVK', isoA2: 'SK' },
  { schluessel: 11, kurz: 'Isle of Man', kfz: 'GBM', isoA3: 'IMN', isoA2: 'IM' },
  { schluessel: 12, kurz: 'Deutschland (ehem. DDR)', kfz: 'D', isoA3: '_19' },
  { schluessel: 13, kurz: 'Dänemark', kfz: 'DK', isoA3: 'DNK', isoA2: 'DK' },
  { schluessel: 14, kurz: 'Niederlande', kfz: 'NL', isoA3: 'NLD', isoA2: 'NL' },
  { schluessel: 15, kurz: 'Belgien', kfz: 'B', isoA3: 'BEL', isoA2: 'BE' },
  { schluessel: 16, kurz: 'Luxemburg', kfz: 'L', isoA3: 'LUX', isoA2: 'LU' },
  { schluessel: 17, kurz: 'Frankreich', kfz: 'F', isoA3: 'FRA', isoA2: 'FR' },
  { schluessel: 18, kurz: 'Spanien', kfz: 'E', isoA3: 'ESP', isoA2: 'ES' },
  { schluessel: 19, kurz: 'Portugal', kfz: 'P', isoA3: 'PRT', isoA2: 'PT' },
  { schluessel: 20, kurz: 'Jersey', kfz: 'GBJ', isoA3: 'JEY', isoA2: 'JE' },
  { schluessel: 21, kurz: 'Bailiwick of Guernsey', kfz: 'GBG', isoA3: 'GGY', isoA2: 'GG' },
  { schluessel: 22, kurz: 'Andorra', kfz: 'AND', isoA3: 'AND', isoA2: 'AD' },
  { schluessel: 23, kurz: 'Monaco', kfz: 'MC', isoA3: 'MCO', isoA2: 'MC' },
  { schluessel: 24, kurz: 'San Marino', kfz: 'RSM', isoA3: 'SMR', isoA2: 'SM' },
  { schluessel: 25, kurz: 'Vatikanstadt', kfz: 'V', isoA3: 'VAT', isoA2: 'VA' },
  { schluessel: 30, kurz: 'Malta', kfz: 'M', isoA3: 'MLT', isoA2: 'MT' },
  { schluessel: 31, kurz: 'Albanien', kfz: 'AL', isoA3: 'ALB', isoA2: 'AL' },
  { schluessel: 32, kurz: 'Griechenland', kfz: 'GR', isoA3: 'GRC', isoA2: 'GR' },
  { schluessel: 33, kurz: 'Türkei', kfz: 'TR', isoA3: 'TUR', isoA2: 'TR' },
  { schluessel: 34, kurz: 'Bulgarien', kfz: 'BG', isoA3: 'BGR', isoA2: 'BG' },
  { schluessel: 35, kurz: 'Rumänien', kfz: 'RO', isoA3: 'ROU', isoA2: 'RO' },
  { schluessel: 36, kurz: 'ehemalige Sowjetunion', isoA3: '_18' },
  { schluessel: 37, kurz: 'Polen', kfz: 'PL', isoA3: 'POL', isoA2: 'PL' },
  { schluessel: 39, kurz: 'Alandinseln', kfz: 'AX', isoA3: 'ALA', isoA2: 'AX' },
  { schluessel: 40, kurz: 'Finnland', kfz: 'FIN', isoA3: 'FIN', isoA2: 'FI' },
  { schluessel: 41, kurz: 'Schweden', kfz: 'S', isoA3: 'SWE', isoA2: 'SE' },
  { schluessel: 42, kurz: 'Norwegen', kfz: 'N', isoA3: 'NOR', isoA2: 'NO' },
  { schluessel: 43, kurz: 'Großbritannien', kfz: 'GB', isoA3: 'GBR', isoA2: 'GB' },
  { schluessel: 44, kurz: 'Irland', kfz: 'IRL', isoA3: 'IRL', isoA2: 'IE' },
  { schluessel: 45, kurz: 'Island', kfz: 'IS', isoA3: 'ISL', isoA2: 'IS' },
  { schluessel: 46, kurz: 'Estland', kfz: 'EST', isoA3: 'EST', isoA2: 'EE' },
  { schluessel: 47, kurz: 'Lettland', kfz: 'LV', isoA3: 'LVA', isoA2: 'LV' },
  { schluessel: 48, kurz: 'Litauen', kfz: 'LT', isoA3: 'LTU', isoA2: 'LT' },
  { schluessel: 51, kurz: 'Slowenien', kfz: 'SLO', isoA3: 'SVN', isoA2: 'SI' },
  { schluessel: 52, kurz: 'Kroatien', kfz: 'HR', isoA3: 'HRV', isoA2: 'HR' },
  { schluessel: 53, kurz: 'Bosnien und Herzegowina', kfz: 'BIH', isoA3: 'BIH', isoA2: 'BA' },
  { schluessel: 54, kurz: 'Nordmazedonien', kfz: 'NMK', isoA3: 'MKD', isoA2: 'MK' },
  { schluessel: 56, kurz: 'Serbien', kfz: 'SRB', isoA3: 'SRB', isoA2: 'RS' },
  { schluessel: 57, kurz: 'Montenegro', kfz: 'MNE', isoA3: 'MNE', isoA2: 'ME' },
  { schluessel: 58, kurz: 'Kosovo', kfz: 'RKS', isoA3: 'XKS', isoA2: 'XK' },
  { schluessel: 60, kurz: 'Russische Föderation', kfz: 'RUS', isoA3: 'RUS', isoA2: 'RU' },
  { schluessel: 61, kurz: 'Belarus (Weißrußland)', kfz: 'BY', isoA3: 'BLR', isoA2: 'BY' },
  { schluessel: 62, kurz: 'Ukraine', kfz: 'UA', isoA3: 'UKR', isoA2: 'UA' },
  { schluessel: 63, kurz: 'Armenien', kfz: 'AM', isoA3: 'ARM', isoA2: 'AM' },
  { schluessel: 64, kurz: 'Aserbaidschan', kfz: 'AZ', isoA3: 'AZE', isoA2: 'AZ' },
  { schluessel: 65, kurz: 'Kasachstan', kfz: 'KZ', isoA3: 'KAZ', isoA2: 'KZ' },
  { schluessel: 66, kurz: 'Moldova', kfz: 'MD', isoA3: 'MDA', isoA2: 'MD' },
  { schluessel: 67, kurz: 'Georgien', kfz: 'GE', isoA3: 'GEO', isoA2: 'GE' },
  { schluessel: 68, kurz: 'Färöer', kfz: 'FR', isoA3: 'FRO', isoA2: 'FO' },
  { schluessel: 69, kurz: 'Gibraltar', kfz: 'GBZ', isoA3: 'GIB', isoA2: 'GI' },
  { schluessel: 70, kurz: 'Svalbard', kfz: 'N', isoA3: 'SJM', isoA2: 'SJ' },
  { schluessel: 100, kurz: 'Asien, nicht näher zuordenbar', isoA3: '_17' },
  { schluessel: 101, kurz: 'Zypern', kfz: 'CY', isoA3: 'CYP', isoA2: 'CY' },
  { schluessel: 102, kurz: 'Israel', kfz: 'IL', isoA3: 'ISR', isoA2: 'IL' },
  { schluessel: 103, kurz: 'Libanon', kfz: 'RL', isoA3: 'LBN', isoA2: 'LB' },
  { schluessel: 104, kurz: 'Jordanien', kfz: 'HKJ', isoA3: 'JOR', isoA2: 'JO' },
  { schluessel: 105, kurz: 'Syrien', kfz: 'SYR', isoA3: 'SYR', isoA2: 'SY' },
  { schluessel: 106, kurz: 'Irak', kfz: 'IRQ', isoA3: 'IRQ', isoA2: 'IQ' },
  { schluessel: 107, kurz: 'Kuwait', kfz: 'KWT', isoA3: 'KWT', isoA2: 'KW' },
  { schluessel: 108, kurz: 'Saudi-Arabien', kfz: 'SA', isoA3: 'SAU', isoA2: 'SA' },
  { schluessel: 109, kurz: 'Jemen (ehem. Demokr. VR)', kfz: 'Y', isoA3: '_16' },
  { schluessel: 110, kurz: 'Jemen', kfz: 'Y', isoA3: 'YEM', isoA2: 'YE' },
  { schluessel: 115, kurz: 'Bahrain', kfz: 'BRN', isoA3: 'BHR', isoA2: 'BH' },
  { schluessel: 116, kurz: 'Katar', kfz: 'Q', isoA3: 'QAT', isoA2: 'QA' },
  { schluessel: 117, kurz: 'Vereinigte Arabische Emirate', kfz: 'UAE', isoA3: 'ARE', isoA2: 'AE' },
  { schluessel: 118, kurz: 'Oman', kfz: 'OM', isoA3: 'OMN', isoA2: 'OM' },
  { schluessel: 119, kurz: 'Iran', kfz: 'IR', isoA3: 'IRN', isoA2: 'IR' },
  { schluessel: 120, kurz: 'Afghanistan', kfz: 'AFG', isoA3: 'AFG', isoA2: 'AF' },
  { schluessel: 125, kurz: 'Pakistan', kfz: 'PK', isoA3: 'PAK', isoA2: 'PK' },
  { schluessel: 126, kurz: 'Indien', kfz: 'IND', isoA3: 'IND', isoA2: 'IN' },
  { schluessel: 127, kurz: 'Nepal', kfz: 'NEP', isoA3: 'NPL', isoA2: 'NP' },
  { schluessel: 128, kurz: 'China', kfz: 'RC', isoA3: 'CHN', isoA2: 'CN' },
  { schluessel: 129, kurz: 'Mongolei', kfz: 'MNL', isoA3: 'MNG', isoA2: 'MN' },
  { schluessel: 130, kurz: 'Bangladesch', kfz: 'BD', isoA3: 'BGD', isoA2: 'BD' },
  { schluessel: 135, kurz: 'Sikkim (zu Indien)', isoA3: '_15' },
  { schluessel: 136, kurz: 'Bhutan', kfz: 'BTN', isoA3: 'BTN', isoA2: 'BT' },
  { schluessel: 137, kurz: 'Myanmar', kfz: 'BUR', isoA3: 'MMR', isoA2: 'MM' },
  { schluessel: 138, kurz: 'Thailand', kfz: 'T', isoA3: 'THA', isoA2: 'TH' },
  { schluessel: 139, kurz: 'Kambodscha', kfz: 'K', isoA3: 'KHM', isoA2: 'KH' },
  { schluessel: 140, kurz: 'Laos', kfz: 'LAO', isoA3: 'LAO', isoA2: 'LA' },
  { schluessel: 144, kurz: 'Brunei', kfz: 'BRU', isoA3: 'BRN', isoA2: 'BN' },
  { schluessel: 145, kurz: 'Malaysia', kfz: 'MAL', isoA3: 'MYS', isoA2: 'MY' },
  { schluessel: 146, kurz: 'Singapur', kfz: 'SGP', isoA3: 'SGP', isoA2: 'SG' },
  { schluessel: 148, kurz: 'Vietnam', kfz: 'VN', isoA3: 'VNM', isoA2: 'VN' },
  { schluessel: 149, kurz: 'Macau (zu Portugal)', kfz: 'MAC', isoA3: 'MAC', isoA2: 'MO' },
  { schluessel: 150, kurz: 'Hongkong', kfz: 'HK', isoA3: 'HKG', isoA2: 'HK' },
  { schluessel: 155, kurz: 'Korea, Dem.VR', kfz: 'PRK', isoA3: 'PRK', isoA2: 'KP' },
  { schluessel: 156, kurz: 'Korea, Rep.', kfz: 'ROK', isoA3: 'KOR', isoA2: 'KR' },
  { schluessel: 157, kurz: 'Malediven', kfz: 'MV', isoA3: 'MDV', isoA2: 'MV' },
  { schluessel: 158, kurz: 'Sri Lanka', kfz: 'CL', isoA3: 'LKA', isoA2: 'LK' },
  { schluessel: 159, kurz: 'Indonesien', kfz: 'RI', isoA3: 'IDN', isoA2: 'ID' },
  { schluessel: 161, kurz: 'Philippinen', kfz: 'RP', isoA3: 'PHL', isoA2: 'PH' },
  { schluessel: 165, kurz: 'Republik China (Taiwan)', kfz: 'RC', isoA3: '_13' },
  { schluessel: 166, kurz: 'Japan', kfz: 'J', isoA3: 'JPN', isoA2: 'JP' },
  { schluessel: 170, kurz: 'Usbekistan', kfz: 'UZ', isoA3: 'UZB', isoA2: 'UZ' },
  { schluessel: 171, kurz: 'Tadschikistan', kfz: 'TJ', isoA3: 'TJK', isoA2: 'TJ' },
  { schluessel: 172, kurz: 'Turkmenistan', kfz: 'TM', isoA3: 'TKM', isoA2: 'TM' },
  { schluessel: 173, kurz: 'Kirgisistan', kfz: 'KS', isoA3: 'KGZ', isoA2: 'KG' },
  { schluessel: 174, kurz: 'Osttimor (alt)', kfz: 'TL', isoA3: 'TMP', isoA2: 'TP' },
  { schluessel: 175, kurz: 'Taiwan', kfz: 'TA', isoA3: 'TWN', isoA2: 'TW' },
  { schluessel: 176, kurz: 'Ostimor / Timor-Leste', kfz: 'TL', isoA3: 'TLS', isoA2: 'TL' },
  { schluessel: 200, kurz: 'Afrika, nicht näher zuordenb.', isoA3: '_12' },
  { schluessel: 201, kurz: 'Marokko', kfz: 'MA', isoA3: 'MAR', isoA2: 'MA' },
  { schluessel: 202, kurz: 'Algerien', kfz: 'DZ', isoA3: 'DZA', isoA2: 'DZ' },
  { schluessel: 203, kurz: 'Tunesien', kfz: 'TN', isoA3: 'TUN', isoA2: 'TN' },
  { schluessel: 204, kurz: 'Libyen', kfz: 'LAR', isoA3: 'LBY', isoA2: 'LY' },
  { schluessel: 205, kurz: 'Ägypten', kfz: 'ET', isoA3: 'EGY', isoA2: 'EG' },
  { schluessel: 206, kurz: 'Sahara (dzt. zu Marokko)', isoA3: '_11' },
  { schluessel: 207, kurz: 'Mauretanien', kfz: 'RIM', isoA3: 'MRT', isoA2: 'MR' },
  { schluessel: 208, kurz: 'Senegal', kfz: 'SN', isoA3: 'SEN', isoA2: 'SN' },
  { schluessel: 209, kurz: 'Gambia', kfz: 'WAG', isoA3: 'GMB', isoA2: 'GM' },
  { schluessel: 210, kurz: 'Mali', kfz: 'RMM', isoA3: 'MLI', isoA2: 'ML' },
  { schluessel: 215, kurz: 'Burkina Faso', kfz: 'BF', isoA3: 'BFA', isoA2: 'BF' },
  { schluessel: 216, kurz: 'Niger', kfz: 'RN', isoA3: 'NER', isoA2: 'NE' },
  { schluessel: 217, kurz: 'Tschad', kfz: 'TCH', isoA3: 'TCD', isoA2: 'TD' },
  { schluessel: 218, kurz: 'Sudan', kfz: 'SUD', isoA3: 'SDN', isoA2: 'SD' },
  { schluessel: 219, kurz: 'Äthiopien', kfz: 'ETH', isoA3: 'ETH', isoA2: 'ET' },
  { schluessel: 220, kurz: 'Somalia', kfz: 'SO', isoA3: 'SOM', isoA2: 'SO' },
  { schluessel: 221, kurz: 'Eritrea', kfz: 'ER', isoA3: 'ERI', isoA2: 'ER' },
  { schluessel: 225, kurz: 'Dschibuti', kfz: 'DJI', isoA3: 'DJI', isoA2: 'DJ' },
  { schluessel: 226, kurz: 'Guinea-Bissau', kfz: 'GNB', isoA3: 'GNB', isoA2: 'GW' },
  { schluessel: 227, kurz: 'Guinea', kfz: 'GN', isoA3: 'GIN', isoA2: 'GN' },
  { schluessel: 228, kurz: 'Sierra Leone', kfz: 'WAL', isoA3: 'SLE', isoA2: 'SL' },
  { schluessel: 229, kurz: 'Liberia', kfz: 'LB', isoA3: 'LBR', isoA2: 'LR' },
  { schluessel: 230, kurz: 'Elfenbeinküste', kfz: 'CI', isoA3: 'CIV', isoA2: 'CI' },
  { schluessel: 235, kurz: 'Ghana', kfz: 'GH', isoA3: 'GHA', isoA2: 'GH' },
  { schluessel: 236, kurz: 'Togo', kfz: 'TG', isoA3: 'TGO', isoA2: 'TG' },
  { schluessel: 237, kurz: 'Benin', kfz: 'DY', isoA3: 'BEN', isoA2: 'BJ' },
  { schluessel: 238, kurz: 'Nigeria', kfz: 'WAN', isoA3: 'NGA', isoA2: 'NG' },
  { schluessel: 239, kurz: 'Kamerun', kfz: 'CAM', isoA3: 'CMR', isoA2: 'CM' },
  { schluessel: 240, kurz: 'Zentralafrikanische Republik', kfz: 'RCA', isoA3: 'CAF', isoA2: 'CF' },
  { schluessel: 245, kurz: 'Äquatorialguinea', kfz: 'GQ', isoA3: 'GNQ', isoA2: 'GQ' },
  { schluessel: 246, kurz: 'Gabun', kfz: 'G', isoA3: 'GAB', isoA2: 'GA' },
  { schluessel: 247, kurz: 'Kongo (Brazzaville)', kfz: 'RCB', isoA3: 'COG', isoA2: 'CG' },
  { schluessel: 248, kurz: 'Kongo (Kin)', kfz: 'ZRE', isoA3: 'COD', isoA2: 'CD' },
  { schluessel: 249, kurz: 'Uganda', kfz: 'EAU', isoA3: 'UGA', isoA2: 'UG' },
  { schluessel: 250, kurz: 'Ruanda', kfz: 'RWA', isoA3: 'RWA', isoA2: 'RW' },
  { schluessel: 251, kurz: 'Südsudan', kfz: 'SSD', isoA3: 'SSD', isoA2: 'SS' },
  { schluessel: 255, kurz: 'Burundi', kfz: 'RU', isoA3: 'BDI', isoA2: 'BI' },
  { schluessel: 256, kurz: 'Tansania', kfz: 'EAT', isoA3: 'TZA', isoA2: 'TZ' },
  { schluessel: 257, kurz: 'Kenia', kfz: 'EAK', isoA3: 'KEN', isoA2: 'KE' },
  { schluessel: 258, kurz: 'Angola', kfz: 'ANG', isoA3: 'AGO', isoA2: 'AO' },
  { schluessel: 259, kurz: 'Sambia', kfz: 'Z', isoA3: 'ZMB', isoA2: 'ZM' },
  { schluessel: 260, kurz: 'Malawi', kfz: 'MW', isoA3: 'MWI', isoA2: 'MW' },
  { schluessel: 265, kurz: 'Mosambik', kfz: 'MOC', isoA3: 'MOZ', isoA2: 'MZ' },
  { schluessel: 266, kurz: 'Namibia', kfz: 'NAM', isoA3: 'NAM', isoA2: 'NA' },
  { schluessel: 268, kurz: 'Südafrika', kfz: 'ZA', isoA3: 'ZAF', isoA2: 'ZA' },
  { schluessel: 269, kurz: 'Botsuana', kfz: 'BW', isoA3: 'BWA', isoA2: 'BW' },
  { schluessel: 270, kurz: 'Simbabwe', kfz: 'ZW', isoA3: 'ZWE', isoA2: 'ZW' },
  { schluessel: 275, kurz: 'Lesotho', kfz: 'LS', isoA3: 'LSO', isoA2: 'LS' },
  { schluessel: 276, kurz: 'Swasiland', kfz: 'SD', isoA3: 'SWZ', isoA2: 'SZ' },
  { schluessel: 277, kurz: 'Madagaskar', kfz: 'RM', isoA3: 'MDG', isoA2: 'MG' },
  { schluessel: 278, kurz: 'Mauritius', kfz: 'MS', isoA3: 'MUS', isoA2: 'MU' },
  { schluessel: 280, kurz: 'Seychellen', kfz: 'SY', isoA3: 'SYC', isoA2: 'SC' },
  { schluessel: 281, kurz: 'Capo Verde', kfz: 'CV', isoA3: 'CPV', isoA2: 'CV' },
  { schluessel: 282, kurz: 'Komoren', kfz: 'COM', isoA3: 'COM', isoA2: 'KM' },
  { schluessel: 283, kurz: 'Sao Tome und Principe', kfz: 'STP', isoA3: 'STP', isoA2: 'ST' },
  { schluessel: 284, kurz: 'Fr.Südgeb.', kfz: 'F', isoA3: 'ATF', isoA2: 'TF' },
  { schluessel: 286, kurz: 'Westsahara', kfz: 'MA', isoA3: 'ESH', isoA2: 'EH' },
  { schluessel: 287, kurz: 'Br.Territ./Ind.Ozean', kfz: 'IO', isoA3: 'IOT', isoA2: 'IO' },
  { schluessel: 288, kurz: 'Mayotte', kfz: 'ME', isoA3: 'MYT', isoA2: 'YT' },
  { schluessel: 289, kurz: 'Reunion', kfz: 'RE', isoA3: 'REU', isoA2: 'RE' },
  { schluessel: 290, kurz: 'St. Helena', kfz: 'SH', isoA3: 'SHN', isoA2: 'SH' },
  { schluessel: 300, kurz: 'Amerika, nicht näher zuordenb.', isoA3: '_01' },
  { schluessel: 301, kurz: 'Kanada', kfz: 'CDN', isoA3: 'CAN', isoA2: 'CA' },
  { schluessel: 302, kurz: 'Vereinigte Staaten (USA)', kfz: 'USA', isoA3: 'USA', isoA2: 'US' },
  { schluessel: 303, kurz: 'Grönland (zu Dänemark)', kfz: 'GL', isoA3: 'GRL', isoA2: 'GL' },
  { schluessel: 304, kurz: 'Mexiko', kfz: 'MEX', isoA3: 'MEX', isoA2: 'MX' },
  { schluessel: 307, kurz: 'Guatemala', kfz: 'GCA', isoA3: 'GTM', isoA2: 'GT' },
  { schluessel: 308, kurz: 'Belize', kfz: 'BH', isoA3: 'BLZ', isoA2: 'BZ' },
  { schluessel: 309, kurz: 'Honduras', kfz: 'HD', isoA3: 'HND', isoA2: 'HN' },
  { schluessel: 310, kurz: 'El Salvador', kfz: 'ES', isoA3: 'SLV', isoA2: 'SV' },
  { schluessel: 315, kurz: 'Nicaragua', kfz: 'NIC', isoA3: 'NIC', isoA2: 'NI' },
  { schluessel: 316, kurz: 'Costa Rica', kfz: 'CR', isoA3: 'CRI', isoA2: 'CR' },
  { schluessel: 317, kurz: 'Panama', kfz: 'PA', isoA3: 'PAN', isoA2: 'PA' },
  { schluessel: 318, kurz: 'Kuba', kfz: 'C', isoA3: 'CUB', isoA2: 'CU' },
  { schluessel: 319, kurz: 'Jamaika', kfz: 'JA', isoA3: 'JAM', isoA2: 'JM' },
  { schluessel: 320, kurz: 'Haiti', kfz: 'RH', isoA3: 'HTI', isoA2: 'HT' },
  { schluessel: 325, kurz: 'Dominikanische Republik', kfz: 'DOM', isoA3: 'DOM', isoA2: 'DO' },
  { schluessel: 326, kurz: 'Puerto Rico (zu USA)', kfz: 'PRI', isoA3: 'PRI', isoA2: 'PR' },
  { schluessel: 327, kurz: 'Bahamas', kfz: 'BS', isoA3: 'BHS', isoA2: 'BS' },
  { schluessel: 328, kurz: 'Bermuda', kfz: 'BMU', isoA3: 'BMU', isoA2: 'BM' },
  { schluessel: 329, kurz: 'Westindische assoz.Staaten', isoA3: '_08' },
  { schluessel: 330, kurz: 'Guadeloupe (zu Frankreich)', kfz: 'GLP', isoA3: 'GLP', isoA2: 'GP' },
  { schluessel: 331, kurz: 'Martinique (zu Frankreich)', kfz: 'MTQ', isoA3: 'MTQ', isoA2: 'MQ' },
  { schluessel: 332, kurz: 'Barbados', kfz: 'BDS', isoA3: 'BRB', isoA2: 'BB' },
  { schluessel: 333, kurz: 'Niederländische Antillen', kfz: 'NA', isoA3: 'ANT', isoA2: 'AN' },
  { schluessel: 337, kurz: 'Kolumbien', kfz: 'CO', isoA3: 'COL', isoA2: 'CO' },
  { schluessel: 338, kurz: 'Venezuela', kfz: 'YV', isoA3: 'VEN', isoA2: 'VE' },
  { schluessel: 339, kurz: 'Guyana', kfz: 'GUY', isoA3: 'GUY', isoA2: 'GY' },
  { schluessel: 340, kurz: 'Suriname', kfz: 'SME', isoA3: 'SUR', isoA2: 'SR' },
  { schluessel: 345, kurz: 'Französisch-Guayana', kfz: 'GF', isoA3: 'GUF', isoA2: 'GF' },
  { schluessel: 346, kurz: 'Trinidad und Tobago', kfz: 'TT', isoA3: 'TTO', isoA2: 'TT' },
  { schluessel: 347, kurz: 'Ecuador', kfz: 'EC', isoA3: 'ECU', isoA2: 'EC' },
  { schluessel: 348, kurz: 'Peru', kfz: 'PE', isoA3: 'PER', isoA2: 'PE' },
  { schluessel: 349, kurz: 'Brasilien', kfz: 'BR', isoA3: 'BRA', isoA2: 'BR' },
  { schluessel: 350, kurz: 'Bolivien', kfz: 'BOL', isoA3: 'BOL', isoA2: 'BO' },
  { schluessel: 355, kurz: 'Paraguay', kfz: 'PY', isoA3: 'PRY', isoA2: 'PY' },
  { schluessel: 356, kurz: 'Chile', kfz: 'RCH', isoA3: 'CHL', isoA2: 'CL' },
  { schluessel: 357, kurz: 'Argentinien', kfz: 'RA', isoA3: 'ARG', isoA2: 'AR' },
  { schluessel: 358, kurz: 'Uruguay', kfz: 'ROU', isoA3: 'URY', isoA2: 'UY' },
  { schluessel: 361, kurz: 'Falklandinseln (zu GB)', kfz: 'FLK', isoA3: 'FLK', isoA2: 'FK' },
  { schluessel: 362, kurz: 'Süd-Georgien', isoA3: '_07' },
  { schluessel: 363, kurz: 'Süd-Sandwich-Inseln', isoA3: '_06' },
  { schluessel: 381, kurz: 'Grenada', kfz: 'WG', isoA3: 'GRD', isoA2: 'GD' },
  { schluessel: 382, kurz: 'Dominica', kfz: 'WD', isoA3: 'DMA', isoA2: 'DM' },
  { schluessel: 383, kurz: 'St. Lucia', kfz: 'WL', isoA3: 'LCA', isoA2: 'LC' },
  { schluessel: 384, kurz: 'St. Vincent und Grenadinen', kfz: 'WV', isoA3: 'VCT', isoA2: 'VC' },
  { schluessel: 385, kurz: 'Antigua und Barbuda', kfz: 'ANT', isoA3: 'ATG', isoA2: 'AG' },
  { schluessel: 386, kurz: 'St. Kitts und Nevis', kfz: 'KN', isoA3: 'KNA', isoA2: 'KN' },
  { schluessel: 387, kurz: 'Aruba', kfz: 'AW', isoA3: 'ABW', isoA2: 'AW' },
  { schluessel: 388, kurz: 'Anguilla', kfz: 'AI', isoA3: 'AIA', isoA2: 'AI' },
  { schluessel: 389, kurz: 'Kaimaninseln', kfz: 'KY', isoA3: 'CYM', isoA2: 'KY' },
  { schluessel: 390, kurz: 'Montserrat', kfz: 'MSR', isoA3: 'MSR', isoA2: 'MS' },
  { schluessel: 391, kurz: 'St. Pierre', kfz: 'PM', isoA3: 'SPM', isoA2: 'PM' },
  { schluessel: 392, kurz: 'Turks/Caicosinseln', kfz: 'TC', isoA3: 'TCA', isoA2: 'TC' },
  { schluessel: 393, kurz: 'Br. Jungferninseln', kfz: 'VG', isoA3: 'VGB', isoA2: 'VG' },
  { schluessel: 394, kurz: 'Amerik. Jungferninseln', kfz: 'VI', isoA3: 'VIR', isoA2: 'VI' },
  { schluessel: 400, kurz: 'Australien/Ozeanien div.', isoA3: '_05' },
  { schluessel: 401, kurz: 'Australien', kfz: 'AUS', isoA3: 'AUS', isoA2: 'AU' },
  { schluessel: 405, kurz: 'Neuseeland', kfz: 'NZ', isoA3: 'NZL', isoA2: 'NZ' },
  { schluessel: 406, kurz: 'Palau', kfz: 'PW', isoA3: 'PLW', isoA2: 'PW' },
  { schluessel: 410, kurz: 'Marianen (zu USA)', kfz: 'MNP', isoA3: 'MNP', isoA2: 'MP' },
  { schluessel: 411, kurz: 'Guam (zu USA)', kfz: 'GU', isoA3: 'GUM', isoA2: 'GU' },
  { schluessel: 412, kurz: 'Hawaii (zu USA)', isoA3: '_04' },
  { schluessel: 413, kurz: 'Marshallinseln', kfz: 'MH', isoA3: 'MHL', isoA2: 'MH' },
  { schluessel: 414, kurz: 'Mikronesien', kfz: 'FSM', isoA3: 'FSM', isoA2: 'FM' },
  { schluessel: 415, kurz: 'Nauru', kfz: 'WAI', isoA3: 'NRU', isoA2: 'NR' },
  { schluessel: 416, kurz: 'Belau (Palau-Inseln)', isoA3: '_03' },
  { schluessel: 420, kurz: 'Kiribati (Gilbert-Inseln)', kfz: 'KIR', isoA3: 'KIR', isoA2: 'KI' },
  { schluessel: 421, kurz: 'Salomonen', kfz: 'SLB', isoA3: 'SLB', isoA2: 'SB' },
  { schluessel: 422, kurz: 'Tuvalu (Ellice-Inseln)', kfz: 'TUV', isoA3: 'TUV', isoA2: 'TV' },
  { schluessel: 423, kurz: 'Vanuatu (neue Hebriden)', kfz: 'VU', isoA3: 'VUT', isoA2: 'VU' },
  { schluessel: 424, kurz: 'Neukaledonien (zu F)', kfz: 'NCL', isoA3: 'NCL', isoA2: 'NC' },
  { schluessel: 427, kurz: 'Fidschi', kfz: 'FJI', isoA3: 'FJI', isoA2: 'FJ' },
  { schluessel: 428, kurz: 'Samoa', kfz: 'WS', isoA3: 'WSM', isoA2: 'WS' },
  { schluessel: 429, kurz: 'Tonga', kfz: 'TO', isoA3: 'TON', isoA2: 'TO' },
  { schluessel: 431, kurz: 'Papua-Neuguinea', kfz: 'PNG', isoA3: 'PNG', isoA2: 'PG' },
  { schluessel: 432, kurz: 'Kokosinseln', kfz: 'CC', isoA3: 'CCK', isoA2: 'CC' },
  { schluessel: 433, kurz: 'Weihnachtsinsel', kfz: 'CX', isoA3: 'CXR', isoA2: 'CX' },
  { schluessel: 434, kurz: 'Cookinseln', kfz: 'CK', isoA3: 'COK', isoA2: 'CK' },
  { schluessel: 435, kurz: 'Heard/McDonaldinseln', kfz: 'HM', isoA3: 'HMD', isoA2: 'HM' },
  { schluessel: 436, kurz: 'Norfolkinseln', kfz: 'NF', isoA3: 'NFK', isoA2: 'NF' },
  { schluessel: 437, kurz: 'Niue', kfz: 'NU', isoA3: 'NIU', isoA2: 'NU' },
  { schluessel: 438, kurz: 'Pitcairn', kfz: 'PN', isoA3: 'PCN', isoA2: 'PN' },
  { schluessel: 439, kurz: 'Tokelau', kfz: 'TK', isoA3: 'TKL', isoA2: 'TK' },
  { schluessel: 440, kurz: 'Kl.Amerik.Überseeinseln', kfz: 'UM', isoA3: 'UMI', isoA2: 'UM' },
  { schluessel: 441, kurz: 'Wallis/Futuna', kfz: 'WF', isoA3: 'WLF', isoA2: 'WF' },
  { schluessel: 442, kurz: 'Amerik.  Samoa', kfz: 'AS', isoA3: 'ASM', isoA2: 'AS' },
  { schluessel: 443, kurz: 'Französisch-Polynesien', kfz: 'F', isoA3: 'PYF', isoA2: 'PF' },
  { schluessel: 500, kurz: 'Antarktis', isoA3: 'ATA', isoA2: 'AQ' },
  { schluessel: 501, kurz: 'Bouvetinseln', kfz: 'BV', isoA3: 'BVT', isoA2: 'BV' },
  { schluessel: 544, kurz: 'Palästina/Westjordanland-Gaza', kfz: 'PAL', isoA3: 'PSE', isoA2: 'PS' },
  { schluessel: 999, kurz: 'Staatsbürgerschaft unbekannt', isoA3: 'unb', isoA2: 'XU' },
]);

/** Alle ISOA3-Codes der Tabelle — der Wertevorrat von `STSL`. */
export const STAATSANGEHOERIGKEITEN: ReadonlySet<string> = new Set(STAATEN.map((s) => s.isoA3));
